<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/workspace/downloadvar/app/modules/Default/config/autoload.xml
// Generated by: AgaviAutoloadConfigHandler
// Date: 2013-07-08T06:43:21+0000

return array (
  'downloadvarDefaultBaseAction' => 'C:\\workspace\\downloadvar\\app/modules/Default/lib/action/downloadvarDefaultBaseAction.class.php',
  'downloadvarDefaultBaseModel' => 'C:\\workspace\\downloadvar\\app/modules/Default/lib/model/downloadvarDefaultBaseModel.class.php',
  'downloadvarDefaultBaseView' => 'C:\\workspace\\downloadvar\\app/modules/Default/lib/view/downloadvarDefaultBaseView.class.php',
);

?>