<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/workspace/downloadvar/app/modules/Default/config/config_handlers.xml
// Generated by: AgaviConfigHandlersConfigHandler
// Date: 2013-07-08T06:43:21+0000

return array (
)

?>