<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/workspace/downloadvar/app/modules/Default/validate/Error404.xml
// Generated by: AgaviValidatorConfigHandler
// Date: 2013-07-08T06:43:22+0000



?>